---
title: "Folie 1"
format:
  revealjs:
    theme: simple
    slide-number: true
    navigation-mode: vertical
    incremental: false
    toc: false
    code-overflow: wrap
---

<style>
.flex-row{display:flex; gap:1rem; align-items:flex-start; justify-content:space-between;}
.flex-row .col{flex:1; min-width:0}
.smalltxt{font-size:0.9em}
.tinytxt{font-size:0.8em}
.ctxt{display:flex; align-items:center; justify-content:center}
</style>


## Welche Lerntypen gibt es?

<div class="flex-row">
<div class="col1">

- 1

- programmieren und datenbanken - daten und funktionen

</div>
<div class="col1">

- The Sixth Sense

</div>
</div>


---


## Lerntypen

<div class="flex-row">
<div class="col1">

- 2

- programmieren und datenbanken - daten und funktionen

- Jeder von uns hat bevorzugte SinneskanäleÜber diese nehmen wir bevorzugt Informationen auf und senden diese ausDies kann man gezielt zum Lernen nutzenAm effektivsten lernt man wenn man verschiedene Kanäle nutzt

- Visuell

</div>
<div class="col1">

- Taktil

- Auditiv

</div>
</div>


---


## Notizen

<div class="flex-row">
<div class="col1">

- 3

- programmieren und datenbanken - daten und funktionen

- Sie sollten sich immer Notizen machen(weil wir uns geschriebenes taktil und visuell besser merken)Sie sollten nicht die Folien abschreiben, sondern eher Schlüsselinformationen, Begriffe und FragenSie sollten sich die Zeit nehmen um Notizen nachzuarbeiten, Fragen zu klären und Inhalte selbst zu strukturieren

</div>
<div class="col1">

- Vorlesung

- Nacharbeit

</div>
</div>


---


## Notizen

<div class="flex-row">
<div class="col1">

- 4

- programmieren und datenbanken - daten und funktionen

</div>
<div class="col1">

- Zum Nachbearbeiten nutzt die SQ3R-Methode

- https://youtu.be/n0ql-yeY9u0

- https://youtu.be/NONST7mwhX8

</div>
</div>


---
