---
title: Programmierung<br>& Datenbanken
subtitle: "Prüfung"
author: "Joern Ploennigs"
format:
  revealjs:
    theme: [white, custom.scss]
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/ai4sc_logo_v2.svg
    footer: |
      <span style="letter-spacing: .04rem;">programmierung</span><br><span style="letter-spacing: .0rem;">und datenbanken</span>
    transition: slide
    transition-speed: fast
    menu:
      side: left
    slide-number: true
    date-format: long
    auto-play-media: true
    template-partials:
      - title-slide.html 
    title-slide-attributes:
      data-background-color: black
      data-background-video: images/01a_Ueberblick/mj_title.mp4
      data-background-video-loop: true
      data-background-video-muted: true
    verticator:
      themetag: 'h1'
      autogenerate: true
revealjs-plugins:
  - verticator
---

# Programmieren und Datenbanken {.center}

**Prüfung und Ausblick**



## CAD UND BIM

::: {.flex}
::: {.flex-item}
**Parametric Building Information Model**

*Generated with Midjourney*
:::
:::



## Vorlesungsplanung

::: {.flex}
::: {.flex-item style="width: 50%"}
**Grundlagen**
- Motivation und Beispiele
- Grundlagen der CAD Modellierung
- Koordinatensysteme & Georeferenzierung

**2D Modellierung**
- Mit Grundkörpern und Geom. Operationen
- Freiformmodellierung mit Splines
:::

::: {.flex-item style="width: 50%"}
**3D Modellierung**
- Mit Grundkörpern und Geom. Operationen
- Freiformmodellierung mit Mesh & Nurbs

**BIM**
- Datenaustausch und Building Information Models
- BIM Struktur, Standardobjekte
- BIM Projektplanung, BIM Ausführung
:::
:::



## Wahlmodul: Entwurfsvisualisierung und Virtuelles Planen

::: {.flex}
::: {.flex-item style="width: 60%"}
**Fokus:** Fortgeschrittene Computerwerkzeuge zur Visualisierung und Planung

**Aspekte:**
- Bildbearbeitung
- Video- und Tonbearbeitung
- 3D-Rendering und Simulation
- Virtual und Augmented Reality
:::

::: {.flex-item style="width: 40%"}
**Vorlesung:** Vermittelt die Grundlagen verschiedener aktueller Technologien und digitaler Werkzeugketten

**Projekt:** Anfertigen von Entwürfen über mehrere Formate hinweg (3D-Modelle, Mappen, Videos, etc.)
:::
:::



## Wahlmodul: Grundlagen Maschinelles Lernen

**Fokus:** Einführung in Methoden der Datenanalyse und des Maschinellen Lernens

**Vorlesung:** Grundlagen verschiedener aktueller Technologien und digitaler Werkzeugketten

**Übung:** Praktische Aufgaben aus der Gebäude- und Umweltdatenanalyse und zur Vorhersage und Klassifikation mit ML Modellen



# Prüfungsthemen {.center}

*Student learning for exams during party - Generated with Midjourney*



## Klausur

::: {.flex}
::: {.flex-item style="width: 50%"}
**Organisation:**
- **Relevant:** Themen auf StudIP
- **Format:** Schriftliche Klausur, ohne mitgebrachte Bücher oder Notizen
- **Dauer:** 90 Minuten
:::

::: {.flex-item style="width: 50%"}
**Grundidee:**
- Handschriftlichen Text reduzieren, eher: Lückentexte, Tabellen, Kurzdefinitionen, Skizzen
- Möglichst wenig „Programmieren auf Papier", eher:
  - Vorgegebene Grundstruktur ausfüllen (z.B. SQL-Klausel mit Lücken)
  - Zu vorgegebenem Code Fragen beantworten
:::
:::



## Arten von Aufgaben

::: {.flex}
::: {.flex-item style="width: 50%"}
**Vorlesungs-bezogene Aufgaben:**
- **Begriffswissen:** „Wie definiert man ...?" „Ordnen sie folgende Begriffe ..."
- **Begriffsverständnis:** „Warum wird in Python ...?" „Wie können ... entstehen?"
- **Modellierung:** „Zeichnen sie ein Diagramm welches ..." „Skizzieren sie ..."
- **Berechnungen:** „Führen sie folgende Operationen aus ..."
:::

::: {.flex-item style="width: 50%"}
**Übungs-bezogene Aufgaben:**
- **Code verstehen:** „Wo liegen hier Fehler?" „Welchen Wert hat im vorliegenden Code ..."
- **Code erstellen:** Ausfüllen/Zuordnen von vorgegebenen Statements/Bausteinen (Python und SQL)
:::
:::



# Hörsaalfrage {.center}

## FRAGEN FRAGEN

*Student asking questions in lecture hall - Generated with Midjourney*



## Vielen Dank für Ihre Aufmerksamkeit! {.center}

**Fragen?**