project:
  title: "Ingenieursinformatik"
  type: website
  output-dir: "_site"
  render:
    - 01a_Ueberblick.qmd
    - 01b_Programmiersprachen.qmd
    - 01c_AgentischesProgrammieren.qmd
    - 02a_Computerhardware.qmd
    - 02b_Speicher.qmd
    - 02c_Datentypen.qmd
    - 03a_Wissenspyramide.qmd
    - 03b_Softwarearchitektur.qmd
    - 03c_Softwareentwurf.qmd
    - 04a_Anforderungen.qmd
    - 04b_Programmablauf.qmd
    - 04c_Objects.qmd
    - 05a_Operatoren.qmd
    - 05b_Verzweigung.qmd
    - 05c_Schleifen.qmd
    - 06a_Funktionen.qmd
    - 06b_Objects.qmd
    - 06c_Module.qmd
    - 07a_Exceptions.qmd
    - 07b_Debugging.qmd
    - 08a_UnitTest.qmd
    - 08b_CodeReview.qmd
    - 09a_Algorithmen.qmd
    - 09b_Rekursion.qmd
    - 10a_Graphprobleme.qmd
    - 10b_Geometrieprobleme.qmd
    - 11a_Raster_Simulation.qmd
    - 11b_UIDesign.qmd
    - 12a_Datenhaltung.qmd
    - 12b_Datenbanktypen.qmd
    - 12c_Datenbanken_Entwurf.qmd
    - 13a_RelationaleDatenbanken.qmd
    - 13b_Datenbanken_SQL_Select.qmd
    - 13c_Datenbanken_SQL_Create.qmd

website:
  navbar:
    logo: lectures/images/pd_logo2.svg
    logo-alt: "Programmierung und Datenbanken Logo"
    background: primary
    collapse: true
    search: true
    left:
      - href: index.qmd
        text: Start
      - text: Grundlagen
        menu:
        - 01a_Ueberblick.qmd
        - 01b_Programmiersprachen.qmd
        - 01c_AgentischesProgrammieren.qmd
        - 02a_Computerhardware.qmd
        - 02b_Speicher.qmd
        - 02c_Datentypen.qmd
      - text: Entwurf
        menu:
        - 03a_Wissenspyramide.qmd
        - 03b_Softwarearchitektur.qmd
        - 03c_Softwareentwurf.qmd
        - 04a_Anforderungen.qmd
        - 04b_Programmablauf.qmd
        - 04c_Objects.qmd
      - text: Programmierung
        menu:
        - 05a_Operatoren.qmd
        - 05b_Verzweigung.qmd
        - 05c_Schleifen.qmd
        - 06a_Funktionen.qmd
        - 06b_Objects.qmd
        - 06c_Module.qmd
      - text: Verifikation
        menu:
        - 07a_Exceptions.qmd
        - 07b_Debugging.qmd
        - 08a_UnitTest.qmd
        - 08b_CodeReview.qmd
      - text: Problemklassen
        menu:
        - 09a_Algorithmen.qmd
        - 09b_Rekursion.qmd
        - 10a_Graphprobleme.qmd
        - 10b_Geometrieprobleme.qmd
        - 11a_Raster_Simulation.qmd
        - 11b_UIDesign.qmd
      - text: Datenmanagement
        menu:
        - 12a_Datenhaltung.qmd
        - 12b_Datenbanktypen.qmd
        - 12c_Datenbanken_Entwurf.qmd
        - 13a_RelationaleDatenbanken.qmd
        - 13b_Datenbanken_SQL_Select.qmd
        - 13c_Datenbanken_SQL_Create.qmd
  favicon: images/pd_logo2.svg

format:
  ai4sc-style-html:
    theme:
      light:
        - _extensions/ai4sc-style/themes/ai4sc-html.scss
        - _extensions/ai4sc-style/themes/color/warm-bone-html.scss
  typst:
    cover-image: images/ai_logo.pdf
  pdf:
    cover-image: images/ai_logo.pdf
  epub:
    cover-image: images/ai_logo.pdf
  ai4sc-style-revealjs:
    css:
      - _extensions/ai4sc-style/themes/color/warm-bone.css
    footer: |
      <span style="letter-spacing: .03em;">Artificial</span><br><span style="letter-spacing: -.03em;">Intelligence</span>
format-links:
  - ai4sc-style-html
  - format: ai4sc-style-revealjs
    text: Slides
    icon: file-easel
  - format: typst
    text: Document PDF
    icon: file-earmark-pdf
  - format: pdf
    text: Slides PDF
    icon: file-earmark-easel
  - format: epub
    text: eBook
    icon: file-earmark-richtext

jupyter:
  jupytext:
    cell_metadata_filter: '-all'
    main_language: python
    notebook_metadata_filter: '-all'
  kernelspec:
    display_name: introductionmachinelearning
    language: python
    name: python3

execute:
  cache: true       # cache chunk results
  freeze: auto      # skip re-execution if code/inputs unchanged

author: "Joern Ploennigs · AI4SC"
default-image-extension: ""
bibliography: "references.bib"
bibliographystyle: ieee
lang: de

particles:
  particleCount: 500
  particleTheme: binary-mesh
  particleRandomRespawnRatio: 0.24
