project:
  type: website
  output-dir: ../_build/_qsite
  render:
      - "*.qmd"
      - "*.ipynb"

website:
  title: "Programmierung und Datenbanken"
  navbar:
    logo: lectures/images/pd_logo2.svg
    logo-alt: "Programmierung und Datenbanken Logo"
    background: primary
    collapse: true
    search: true
    left:
      - href: index.qmd
        text: Start
      - text: Grundlagen
        menu:
        - href: 01a_Ueberblick.qmd
        - href: 01b_Programmiersprachen.qmd
        - href: 01c_AgentischesProgrammieren.qmd
        - href: 02a_Computerhardware.qmd
        - href: 02b_Speicher.qmd
        - href: 02c_Datentypen.qmd
      - text: Entwurf
        menu:
        - href: 03a_Wissenspyramide.qmd
        - href: 03b_Softwarearchitektur.qmd
        - href: 03c_Softwareentwurf.qmd
        - href: 04a_Anforderungen.qmd
        - href: 04b_Programmablauf.qmd
        - href: 04c_Objects.qmd
      - text: Programmierung
        menu:
        - href: 05a_Operatoren.qmd
        - href: 05b_Verzweigung.qmd
        - href: 05c_Schleifen.qmd
        - href: 06a_Funktionen.qmd
        - href: 06b_Objects.qmd
        - href: 06c_Module.qmd
      - text: Verifikation
        menu:
        - href: 07a_Exceptions.qmd
        - href: 07b_Debugging.qmd
        - href: 08a_UnitTest.qmd
        - href: 08b_CodeReview.qmd
      - text: Problemklassen
        menu:
        - href: 09a_Algorithmen.qmd
        - href: 09b_Rekursion.qmd
        - href: 10a_Graphprobleme.qmd
        - href: 10b_Geometrieprobleme.qmd
        - href: 11a_Raster_Simulation.qmd
        - href: 11b_UIDesign.qmd
      - text: Datenmanagement
        menu:
        - href: 12a_Datenhaltung.qmd
        - href: 12b_Datenbanktypen.qmd
        - href: 12c_Datenbanken_Entwurf.qmd
        - href: 13a_RelationaleDatenbanken.qmd
        - href: 13b_Datenbanken_SQL_Select.qmd
        - href: 13c_Datenbanken_SQL_Create.qmd
  favicon: images/pd_logo2.svg

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3