project:
  type: book
  output-dir: build/_book

book:
  title: "Programmierung und Datenbanken"
  author: "Joern Ploennigs, AI 4 Sustainable Construction, University of Rostock"
  chapters:
    - index.qmd
  page-navigation: true
  sidebar:
    logo: lectures/images/pd_logo2.svg
  cover-image: lectures/images/pd_logo2.svg
  downloads: []
  search: true

format:
  html:
    theme:
      light: cosmo
    number-sections: true
    toc: true
    toc-depth: 3
    comments:
      hypothesis: true
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex
  epub: default

execute:
  execute-notebooks: auto
  timeout: 30
  error: true

bibliography: references.bib

comments:
  hypothesis: true

website:
  site-url: "https://code-book.ai4sc-lehre.auf.uni-rostock.de/"
  repo-url: "https://github.com/ai4sc-lectures/Programmierung-und-Datenbanken"
  repo-actions: [edit, issue]