project:
  type: website
  output-dir: ../_build/_qsite
  render:
      - "*.qmd"
      - "*.ipynb"

website:
  title: "Programmierung und Datenbanken"
  navbar:
    logo: lectures/images/pd_logo2.svg
    logo-alt: "Programmierung und Datenbanken Logo"
    background: primary
    collapse: true
    search: true
    left:
      - href: index.qmd
        text: Start
      - text: Grundlagen
        menu:
        - href: 01c_Computerhardware.ipynb
        - href: 01d_Programmiersprachen.ipynb
        - href: 01e_Softwarearchitektur.ipynb
        - href: 02a_Wissenspyramide.ipynb
        - href: 02b_Datentypen.ipynb
        - href: 02c_Operatoren.ipynb
        - href: 03a_Verzweigung.ipynb
        - href: 03b_Schleifen.ipynb
      - text: Modularisierung
        menu:
        - href: 04a_Funktionen.ipynb
        - href: 04c_Objects.ipynb
        - href: 04b_Rekursion.ipynb
        - href: 05a_Programmablauf.md
        - href: 05b_Algorithmen.ipynb
        - href: 06a_Exceptions.ipynb
        - href: 06b_UnitTest.ipynb
        - href: 06c_Debugging.ipynb
        - href: 07a_Module.ipynb
      - text: Datenbanken
        menu:
        - href: 9_Datenhaltung.ipynb
        - href: 10_Datenbanken.ipynb
        - href: 11_Datenbankentwurf.ipynb
  favicon: images/pd_logo2.svg

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3